### ISSUE TITLE
有没有别的live2d的人物可以更换【痴汉脸】

### ISSUE THREAD

**Issue by LinkinStars** [amorist/platelet#39]
比如弄个蕾姆或者2333娘什么的

**Comment by amorist** [comment]
我看看，找时间实现一个可以更换live2d的软件。

**Comment by binglumeng** [comment]
https://github.com/sunqibuhuake/atom-miku
大佬可以参照初音未来这个项目，移植一下,做成可运行程序。

**Comment by amorist** [comment]
好的 我周末看看哈

**Comment by amorist** [comment]
目前已经初步完成，还请帮忙看下可优化的地方 https://github.com/amorist/kanban-musume-desktop/releases
